#!/usr/bin/env node
/**
 * Builds the blog from markdown.
 *
 *   node tools/build-blog.mjs           write post pages, the blog index and the sitemap
 *   node tools/build-blog.mjs --check   fail (exit 1) if any output is out of sync
 *
 * One post is one file: content/blog/<slug>.md. Front matter carries the metadata,
 * the body is markdown (raw HTML blocks pass through untouched, which is how the
 * illustrated posts keep their custom layout). Everything downstream — the page, its
 * card on /blog/, the related-post links, the tag filter, the sitemap entry — is
 * derived from that one file, so a post is never half-published.
 *
 * The nav, footer and chrome CSS come from tools/build-chrome.mjs, which this
 * imports; running either script alone leaves the site consistent.
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT, config, esc, fill, indent, applyChrome, stripComment, replaceRegion } from './build-chrome.mjs';

const SITE = (config.site || '').replace(/\/$/, '');
const CONTENT_DIR = join(ROOT, 'content/blog');
const POSTS_START = '<!-- posts:start — generated by tools/build-blog.mjs, do not edit -->';
const POSTS_END = '<!-- posts:end -->';

const WORDS_PER_MINUTE = 200;
const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'];

const DEFAULT_CTA = {
  title: 'See what this looks like on your documents',
  text: 'Bring a sample of the work you actually process. We will show you the pipeline running on it.',
  label: 'Book a Demo',
  href: '/#contact',
};

// ── Front matter ──────────────────────────────────────────────────────────────

/**
 * A deliberately small YAML subset: `key: value` and `key: [a, b]`. Anything more
 * would mean a dependency, and posts do not need more.
 */
function parseFrontMatter(raw, file) {
  const m = raw.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!m) throw new Error(`${file}: missing --- front matter block.`);
  const data = {};
  for (const line of m[1].split('\n')) {
    if (!line.trim() || line.trimStart().startsWith('#')) continue;
    const at = line.indexOf(':');
    if (at === -1) throw new Error(`${file}: cannot parse front matter line: ${line}`);
    const key = line.slice(0, at).trim();
    let value = line.slice(at + 1).trim();
    if (value.startsWith('[') && value.endsWith(']')) {
      value = value.slice(1, -1).split(',').map((s) => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean);
    } else {
      value = value.replace(/^["']|["']$/g, '');
      if (value === 'true') value = true;
      else if (value === 'false') value = false;
    }
    data[key] = value;
  }
  return { data, body: raw.slice(m[0].length) };
}

// ── Markdown ──────────────────────────────────────────────────────────────────

const escapeText = (s) =>
  s.replace(/&(?![a-zA-Z#][a-zA-Z0-9]*;)/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/** Inline markdown: `code`, [text](href), **bold**, *italic*. Code spans win. */
function inline(text) {
  const codes = [];
  let s = text.replace(/`([^`]+)`/g, (_, c) => `\u0000${codes.push(c) - 1}\u0000`);
  s = escapeText(s);
  s = s.replace(/\[([^\]]+)\]\(([^)\s]+)\)/g, (_, label, href) => `<a href="${href}">${label}</a>`);
  s = s.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  s = s.replace(/(^|[^*])\*([^*\n]+)\*/g, '$1<em>$2</em>');
  return s.replace(/\u0000(\d+)\u0000/g, (_, i) => `<code>${escapeText(codes[i])}</code>`);
}

/**
 * Block-level markdown. Supports headings, paragraphs, bullet and numbered lists,
 * blockquotes, tables, rules, fenced code and raw HTML passthrough — which is the
 * whole vocabulary the posts use.
 */
function markdown(src) {
  const lines = src.replace(/\r\n/g, '\n').split('\n');
  const out = [];
  let i = 0;

  const isBlank = (l) => !l.trim();

  while (i < lines.length) {
    const line = lines[i];

    if (isBlank(line)) { i++; continue; }

    // Fenced code
    if (/^```/.test(line)) {
      const buf = [];
      i++;
      while (i < lines.length && !/^```/.test(lines[i])) buf.push(lines[i++]);
      i++;
      out.push(`<pre><code>${escapeText(buf.join('\n'))}</code></pre>`);
      continue;
    }

    // Raw HTML block — runs to the next blank line, emitted verbatim.
    if (line.trimStart().startsWith('<')) {
      const buf = [];
      while (i < lines.length && !isBlank(lines[i])) buf.push(lines[i++]);
      out.push(buf.join('\n'));
      continue;
    }

    // Horizontal rule
    if (/^---+\s*$/.test(line)) { out.push('<hr>'); i++; continue; }

    // Headings
    const h = line.match(/^(#{2,4})\s+(.*)$/);
    if (h) {
      const level = h[1].length;
      const text = inline(h[2].trim());
      out.push(`<h${level} id="${slugify(h[2])}">${text}</h${level}>`);
      i++;
      continue;
    }

    // Blockquote
    if (/^>\s?/.test(line)) {
      const buf = [];
      while (i < lines.length && /^>\s?/.test(lines[i])) buf.push(lines[i++].replace(/^>\s?/, ''));
      out.push(`<blockquote><p>${inline(buf.join(' ').trim())}</p></blockquote>`);
      continue;
    }

    // Table
    if (line.trimStart().startsWith('|') && /^\s*\|[\s:|-]+\|\s*$/.test(lines[i + 1] || '')) {
      const cells = (l) => l.trim().replace(/^\||\|$/g, '').split('|').map((c) => c.trim());
      const head = cells(lines[i]);
      i += 2;
      const rows = [];
      while (i < lines.length && lines[i].trimStart().startsWith('|')) rows.push(cells(lines[i++]));
      out.push(
        '<div class="post-table-wrap"><table>',
        `<thead><tr>${head.map((c) => `<th>${inline(c)}</th>`).join('')}</tr></thead>`,
        `<tbody>${rows.map((r) => `<tr>${r.map((c) => `<td>${inline(c)}</td>`).join('')}</tr>`).join('')}</tbody>`,
        '</table></div>',
      );
      continue;
    }

    // Lists
    const bullet = /^[-*]\s+/;
    const number = /^\d+\.\s+/;
    if (bullet.test(line) || number.test(line)) {
      const ordered = number.test(line);
      const marker = ordered ? number : bullet;
      const items = [];
      while (i < lines.length && marker.test(lines[i])) {
        let text = lines[i++].replace(marker, '');
        // Continuation lines are indented under their bullet.
        while (i < lines.length && /^\s{2,}\S/.test(lines[i]) && !marker.test(lines[i].trim())) {
          text += ' ' + lines[i++].trim();
        }
        items.push(`  <li>${inline(text.trim())}</li>`);
      }
      const tag = ordered ? 'ol' : 'ul';
      out.push(`<${tag}>`, ...items, `</${tag}>`);
      continue;
    }

    // Paragraph
    const buf = [];
    while (i < lines.length && !isBlank(lines[i]) && !lines[i].trimStart().startsWith('<') && !/^(#{2,4}\s|>|\||```|---+\s*$)/.test(lines[i]) && !bullet.test(lines[i]) && !number.test(lines[i])) {
      buf.push(lines[i++].trim());
    }
    if (buf.length) out.push(`<p>${inline(buf.join(' '))}</p>`);
    else i++;
  }

  return out.join('\n');
}

const slugify = (s) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60);

// ── Posts ─────────────────────────────────────────────────────────────────────

function loadPosts() {
  if (!existsSync(CONTENT_DIR)) return [];
  const posts = [];
  for (const name of readdirSync(CONTENT_DIR).sort()) {
    if (!name.endsWith('.md')) continue;
    const file = `content/blog/${name}`;
    const { data, body } = parseFrontMatter(readFileSync(join(CONTENT_DIR, name), 'utf8'), file);
    if (data.draft) continue;

    for (const key of ['title', 'description', 'date']) {
      if (!data[key]) throw new Error(`${file}: front matter is missing \`${key}\`.`);
    }
    if (!/^\d{4}-\d{2}-\d{2}$/.test(data.date)) throw new Error(`${file}: date must be YYYY-MM-DD.`);

    const slug = data.slug || name.replace(/\.md$/, '');
    const words = body.replace(/<[^>]+>/g, ' ').split(/\s+/).filter(Boolean).length;
    posts.push({
      file,
      slug,
      url: `/blog/${slug}/`,
      // A `custom` post is hand-built HTML with its own layout and stylesheet. It is
      // still indexed, related and sitemapped from here — only its page is not written.
      custom: Boolean(data.custom),
      title: data.title,
      description: data.description,
      date: data.date,
      dateHuman: humanDate(data.date),
      tags: Array.isArray(data.tags) ? data.tags : data.tags ? [data.tags] : [],
      // Editorial pin. Posts published on the same day would otherwise be ordered
      // by slug, which puts whatever starts with "a" at the top of the blog.
      weight: Number(data.weight) || 0,
      highlight: data.highlight || '',
      readTime: Number(data.readTime) || Math.max(3, Math.round(words / WORDS_PER_MINUTE)),
      cta: {
        title: data.ctaTitle || DEFAULT_CTA.title,
        text: data.ctaText || DEFAULT_CTA.text,
        label: data.ctaLabel || DEFAULT_CTA.label,
        href: data.ctaHref || DEFAULT_CTA.href,
      },
      body,
    });
  }
  // Pinned first, then newest, then a stable tiebreak so the output is deterministic.
  posts.sort((a, b) =>
    (b.weight - a.weight) || b.date.localeCompare(a.date) || a.slug.localeCompare(b.slug));
  return posts;
}

function humanDate(iso) {
  const [y, m, d] = iso.split('-').map(Number);
  return `${MONTHS[m - 1]} ${d}, ${y}`;
}

/**
 * Highlight the last few words of the title, the way the hand-written posts did.
 * `highlight` in front matter overrides the guess when the tail is the wrong phrase.
 */
function titleHtml(post) {
  const phrase = post.highlight;
  if (phrase && post.title.includes(phrase)) {
    const at = post.title.indexOf(phrase);
    return esc(post.title.slice(0, at)) +
      `<span class="gradient-text">${esc(phrase)}</span>` +
      esc(post.title.slice(at + phrase.length));
  }
  return esc(post.title);
}

/** Up to three posts sharing the most tags, falling back to the most recent. */
function relatedTo(post, posts) {
  const scored = posts
    .filter((p) => p.slug !== post.slug)
    .map((p) => ({ p, score: p.tags.filter((t) => post.tags.includes(t)).length }))
    .sort((a, b) => (b.score - a.score) || b.p.date.localeCompare(a.p.date) || a.p.slug.localeCompare(b.p.slug));
  return scored.slice(0, 3).map((s) => s.p);
}

function renderRelated(post, posts) {
  const related = relatedTo(post, posts);
  if (!related.length) return '';
  const cards = related.map((p) => [
    `<a href="${p.url}" class="glass rounded-2xl p-5 flex flex-col group no-underline hover:border-white/15 transition-colors">`,
    `  <p class="text-xs text-slate-500 mb-2">${esc(p.tags[0] || 'Insights')}</p>`,
    `  <h3 class="text-sm font-semibold text-white leading-snug mb-2 group-hover:text-indigo-300 transition-colors">${esc(p.title)}</h3>`,
    `  <p class="text-xs text-slate-400 leading-relaxed line-clamp-3">${esc(p.description)}</p>`,
    '</a>',
  ]);
  return [
    '      <section class="mt-16">',
    '        <h2 class="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-5">Keep reading</h2>',
    '        <div class="grid gap-5 sm:grid-cols-3">',
    indent(cards.flat(), '          '),
    '        </div>',
    '      </section>',
  ].join('\n');
}

function renderPost(post, posts, template) {
  const canonical = `${SITE}${post.url}`;
  const jsonld = JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: post.title,
    description: post.description,
    datePublished: post.date,
    dateModified: post.date,
    mainEntityOfPage: canonical,
    url: canonical,
    keywords: post.tags.join(', '),
    author: { '@type': 'Organization', name: 'Xentovia Tech' },
    publisher: {
      '@type': 'Organization',
      name: 'Xentovia Tech',
      logo: { '@type': 'ImageObject', url: `${SITE}/favicon.png` },
    },
  }, null, 2);

  const html = fill(template, {
    TITLE: esc(post.title),
    TITLE_HTML: titleHtml(post),
    DESCRIPTION: esc(post.description),
    CANONICAL: canonical,
    DATE_ISO: post.date,
    DATE_HUMAN: post.dateHuman,
    READ_TIME: String(post.readTime),
    TAGS: indent(post.tags.map((t) => `<span class="tag">${esc(t)}</span>`), '            '),
    BODY: indent(markdown(post.body).split('\n'), '          '),
    CTA_TITLE: esc(post.cta.title),
    CTA_TEXT: esc(post.cta.text),
    CTA_HREF: esc(post.cta.href),
    CTA_LABEL: esc(post.cta.label),
    RELATED: renderRelated(post, posts),
    JSONLD: jsonld,
  });

  return applyChrome(html, {}, `blog/${post.slug}/index.html`);
}

// ── Blog index ────────────────────────────────────────────────────────────────

function renderIndex(posts) {
  const counts = new Map();
  for (const p of posts) for (const t of p.tags) counts.set(t, (counts.get(t) || 0) + 1);
  const tags = [...counts.entries()]
    .sort((a, b) => (b[1] - a[1]) || a[0].localeCompare(b[0]))
    .map(([t]) => t);

  const chips = [
    '<button type="button" class="blog-chip is-active" data-tag="">All <span class="text-slate-500">' + posts.length + '</span></button>',
    ...tags.map((t) => `<button type="button" class="blog-chip" data-tag="${esc(t)}">${esc(t)} <span class="text-slate-500">${counts.get(t)}</span></button>`),
  ];

  const cards = posts.map((p) => [
    `<a href="${p.url}" class="blog-card glass bento-card rounded-2xl p-6 flex flex-col group cursor-pointer no-underline" data-tags="${esc(p.tags.join('|'))}" data-text="${esc((p.title + ' ' + p.description).toLowerCase())}">`,
    '  <div class="flex flex-wrap gap-2 mb-4">',
    ...p.tags.map((t) => `    <span class="tag">${esc(t)}</span>`),
    '  </div>',
    `  <h2 class="text-lg font-bold text-white leading-snug mb-3 group-hover:text-indigo-300 transition-colors">${esc(p.title)}</h2>`,
    `  <p class="text-sm text-slate-400 leading-relaxed mb-6 flex-grow">${esc(p.description)}</p>`,
    '  <div class="flex items-center justify-between mt-auto pt-4 border-t border-white/5">',
    `    <time datetime="${p.date}" class="text-xs text-slate-400">${p.dateHuman}</time>`,
    '    <span class="flex items-center gap-1.5 text-sm font-medium text-indigo-400 group-hover:text-indigo-300 transition-colors">',
    '      Read more',
    '      <i data-lucide="arrow-right" class="w-3.5 h-3.5"></i>',
    '    </span>',
    '  </div>',
    '</a>',
  ]);

  return [
    '      <div class="mb-10">',
    '        <label class="relative block max-w-md mx-auto mb-6">',
    '          <i data-lucide="search" class="w-4 h-4 absolute left-4 top-1/2 -translate-y-1/2 text-slate-500"></i>',
    '          <input id="blogSearch" type="search" placeholder="Search posts" autocomplete="off"',
    '                 class="w-full bg-white/[0.03] border border-white/10 rounded-xl pl-11 pr-4 py-2.5 text-sm text-white placeholder-slate-500 focus:outline-none focus:border-indigo-500/50">',
    '        </label>',
    '        <div id="blogTags" class="flex flex-wrap justify-center gap-2">',
    indent(chips, '          '),
    '        </div>',
    '      </div>',
    '',
    `      <p id="blogCount" class="text-center text-xs text-slate-500 mb-8">${posts.length} posts</p>`,
    '',
    '      <div id="blogGrid" class="grid gap-8 md:grid-cols-2 lg:grid-cols-3">',
    indent(cards.flat(), '        '),
    '      </div>',
    '',
    '      <p id="blogEmpty" class="hidden text-center text-slate-400 py-16">No posts match that search.</p>',
  ].join('\n');
}

// ── Sitemap ───────────────────────────────────────────────────────────────────

function renderSitemap(posts) {
  const urls = [];
  const seen = new Set();
  const add = (loc, lastmod) => {
    if (seen.has(loc)) return;
    seen.add(loc);
    urls.push({ loc, lastmod });
  };

  for (const file of Object.keys(config.pages)) {
    add(SITE + '/' + file.replace(/(^|\/)index\.html$/, '$1').replace(/^\/*/, ''), null);
  }
  for (const p of posts) add(SITE + p.url, p.date);

  const body = urls.map(({ loc, lastmod }) =>
    ['  <url>', `    <loc>${esc(loc)}</loc>`, ...(lastmod ? [`    <lastmod>${lastmod}</lastmod>`] : []), '  </url>'].join('\n'),
  );
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...body,
    '</urlset>',
    '',
  ].join('\n');
}

// ── Main ──────────────────────────────────────────────────────────────────────

function main() {
  const checkOnly = process.argv.includes('--check');
  const posts = loadPosts();
  if (!posts.length) throw new Error('No posts found in content/blog/.');

  const template = stripComment(readFileSync(join(ROOT, 'partials/blog-post.html'), 'utf8')) + '\n';
  const outputs = new Map();

  for (const post of posts) {
    if (post.custom) continue;
    outputs.set(`blog/${post.slug}/index.html`, renderPost(post, posts, template));
  }

  const indexFile = 'blog/index.html';
  const indexHtml = readFileSync(join(ROOT, indexFile), 'utf8');
  outputs.set(indexFile, replaceRegion(indexHtml, POSTS_START, POSTS_END, renderIndex(posts), indexFile));
  outputs.set('sitemap.xml', renderSitemap(posts));

  const stale = [];
  for (const [file, content] of outputs) {
    const path = join(ROOT, file);
    const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
    if (current === content) continue;
    if (checkOnly) stale.push(file);
    else {
      mkdirSync(join(path, '..'), { recursive: true });
      writeFileSync(path, content);
    }
  }

  // A post directory with no markdown source can only be a leftover.
  const slugs = new Set(posts.map((p) => p.slug));
  const orphans = readdirSync(join(ROOT, 'blog'), { withFileTypes: true })
    .filter((e) => e.isDirectory() && !slugs.has(e.name))
    .map((e) => `blog/${e.name}/`);
  if (orphans.length) console.warn('Warning — post directories with no source in content/blog/:\n' + orphans.map((o) => `  ${o}`).join('\n'));

  if (checkOnly && stale.length) {
    console.error('Blog output is out of sync in:\n' + stale.map((f) => `  ${f}`).join('\n'));
    console.error('\nRun `node tools/build-blog.mjs` and commit the result.');
    process.exit(1);
  }
  console.log(checkOnly ? `Blog in sync: ${posts.length} posts.` : `Wrote ${posts.length} posts, the blog index and sitemap.xml.`);
}

main();
