#!/usr/bin/env node
/**
 * Renders the shared page chrome — navigation and footer — into every managed page.
 *
 *   node tools/build-chrome.mjs           write the chrome into each page
 *   node tools/build-chrome.mjs --check   fail (exit 1) if any page is out of sync
 *
 * Pages are the build output as well as the source of truth for everything else,
 * so the generated markup lives between markers and nothing outside them is touched
 * (apart from the `has-subnav` body class, which the sub-nav depends on).
 *
 * The rendering half of this file is also imported by tools/build-blog.mjs, which
 * needs to emit complete pages — chrome included — for posts it creates.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const read = (p) => readFileSync(join(ROOT, p), 'utf8');

const gen = (what, src) => `generated by tools/build-chrome.mjs from partials/${src}, do not edit`;
export const NAV_START = `<!-- nav:start — ${gen('nav', 'nav.html')} -->`;
export const NAV_END = '<!-- nav:end -->';
export const FOOTER_START = `<!-- footer:start — ${gen('footer', 'footer.html')} -->`;
export const FOOTER_END = '<!-- footer:end -->';
export const CSS_START = `/* chrome:start — ${gen('css', 'chrome.css')} */`;
export const CSS_END = '/* chrome:end */';

export const config = JSON.parse(read('partials/chrome.config.json'));
const navTemplate = stripComment(read('partials/nav.html'));
const subnavTemplate = stripComment(read('partials/subnav.html'));
const footerTemplate = stripComment(read('partials/footer.html'));
export const chromeCss = read('partials/chrome.css').trimEnd();

export const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
export const fill = (tpl, vars) => tpl.replace(/\{\{(\w+)\}\}/g, (_, k) => (k in vars ? vars[k] : ''));
export const indent = (lines, pad) => lines.map((l) => pad + l).join('\n');

/** Drop the leading explanatory comment from a partial — it is for editors, not output. */
export function stripComment(tpl) {
  return tpl.replace(/^<!--[\s\S]*?-->\n/, '').trimEnd();
}

/**
 * Every page the chrome is written into: the explicit list in chrome.config.json plus
 * each blog post found on disk. Posts are generated (see tools/build-blog.mjs), so
 * discovering them keeps adding one from turning into a two-file edit.
 */
export function listPages() {
  const pages = { ...config.pages };
  const blogDir = join(ROOT, 'blog');
  if (existsSync(blogDir)) {
    for (const entry of readdirSync(blogDir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const file = `blog/${entry.name}/index.html`;
      if (existsSync(join(ROOT, file)) && !(file in pages)) pages[file] = {};
    }
  }
  return pages;
}

export function renderNav(page) {
  const link = (l, cls) => `<a href="${esc(l.href)}" class="${cls}">${esc(l.label)}</a>`;
  const deskCls = 'text-sm text-slate-400 hover:text-white transition-colors';
  const mobCls = 'block text-sm text-slate-400 hover:text-white py-2';

  /** Emit a group heading whenever `group` changes, so products read as products. */
  const heading = (s, i, cls) =>
    s.group && s.group !== config.solutions[i - 1]?.group
      ? [`<p class="${cls} text-[11px] font-semibold uppercase tracking-wider text-slate-500">${esc(s.group)}</p>`]
      : [];

  const solutionsDesktop = config.solutions.map((s, i) => {
    const current = s.key === page.active;
    const wrap = current
      ? 'flex items-start gap-3 p-2.5 rounded-xl bg-white/[0.06] ring-1 ring-white/10 transition-colors'
      : 'flex items-start gap-3 p-2.5 rounded-xl hover:bg-white/5 transition-colors';
    return [
      ...heading(s, i, 'px-2.5 pt-2 pb-1'),
      `<a href="${esc(s.href)}" class="${wrap}"${current ? ' aria-current="page"' : ''}>`,
      `  <div class="w-8 h-8 rounded-lg flex items-center justify-center bg-${s.color}-500/10 border border-${s.color}-500/20 flex-shrink-0 mt-0.5">`,
      `    <i data-lucide="${esc(s.icon)}" class="w-4 h-4 text-${s.color}-400"></i>`,
      '  </div>',
      '  <div class="min-w-0">',
      `    <p class="text-sm font-semibold text-white">${esc(s.title)}</p>`,
      `    <p class="text-xs text-slate-400 truncate">${esc(s.subtitle)}</p>`,
      '  </div>',
      '</a>',
    ];
  });

  const solutionsMobile = config.solutions.map((s, i) => [
    ...heading(s, i, 'pt-2 pb-0.5'),
    `<a href="${esc(s.href)}" class="block py-1 text-sm text-slate-300 hover:text-white"${s.key === page.active ? ' aria-current="page"' : ''}>` +
      `<span class="font-medium text-white">${esc(s.title)}</span> ` +
      `<span class="text-xs text-slate-400">&middot; ${esc(s.subtitleShort)}</span></a>`,
  ]);

  return fill(navTemplate, {
    LINKS_BEFORE_DESKTOP: indent(config.linksBefore.map((l) => link(l, deskCls)), '      '),
    LINKS_AFTER_DESKTOP: indent(config.linksAfter.map((l) => link(l, deskCls)), '      '),
    LINKS_BEFORE_MOBILE: indent(config.linksBefore.map((l) => link(l, mobCls)), '        '),
    LINKS_AFTER_MOBILE: indent(config.linksAfter.map((l) => link(l, mobCls)), '        '),
    SOLUTIONS_DESKTOP: indent(solutionsDesktop.flat(), '            '),
    SOLUTIONS_MOBILE: indent(solutionsMobile.flat(), '            '),
    CTA_HREF: esc(config.cta.href),
    CTA_LABEL: esc(config.cta.label),
    SUBNAV: page.subnav ? renderSubnav(page.subnav) : '',
  });
}

function renderSubnav(sub) {
  const links = sub.links.map(
    (l) => `<a href="${esc(l.href)}" class="text-sm text-slate-400 hover:text-white transition-colors whitespace-nowrap">${esc(l.label)}</a>`,
  );
  return fill(subnavTemplate, {
    SUBNAV_HREF: esc(sub.href),
    SUBNAV_NAME: esc(sub.name),
    SUBNAV_LINKS: indent(links, '      '),
    SUBNAV_CTA_HREF: esc(sub.cta.href),
    SUBNAV_CTA_LABEL: esc(sub.cta.label),
  });
}

export function renderFooter() {
  const f = config.footer;
  const columns = f.columns.map((col) => {
    const items = [];
    if (col.fromSolutions) {
      for (const s of config.solutions.filter((s) => s.group === col.fromSolutions)) {
        items.push({ label: s.subtitleShort, href: s.href });
      }
    }
    items.push(...(col.links ?? []));
    return [
      '<div>',
      `  <h4 class="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-4">${esc(col.title)}</h4>`,
      '  <ul class="space-y-2.5">',
      ...items.map(
        (l) => `    <li><a href="${esc(l.href)}" class="text-sm text-slate-400 hover:text-white transition-colors">${esc(l.label)}</a></li>`,
      ),
      '  </ul>',
      '</div>',
    ];
  });

  return fill(footerTemplate, {
    TAGLINE: esc(f.tagline),
    EMAIL: esc(f.email),
    LINKEDIN: esc(f.linkedin),
    COPYRIGHT: esc(f.copyright).replace('©', '&copy;'),
    COLUMNS: indent(columns.flat(), '      '),
  });
}

/** Replace the region between `start` and `end` markers. Throws if they are missing. */
export function replaceRegion(html, start, end, body, file) {
  const a = html.indexOf(start);
  const b = html.indexOf(end, a);
  if (a === -1 || b === -1) {
    throw new Error(`${file}: missing ${start.slice(0, 20)}… / ${end} markers.`);
  }
  return html.slice(0, a) + start + '\n' + body + '\n' + html.slice(b);
}

export function setBodyClass(html, cls, enabled) {
  return html.replace(/<body([^>]*)>/, (tag, attrs) => {
    const m = attrs.match(/\sclass="([^"]*)"/);
    const names = new Set(m ? m[1].split(/\s+/).filter(Boolean) : []);
    enabled ? names.add(cls) : names.delete(cls);
    const value = [...names].join(' ');
    if (m) return `<body${attrs.replace(m[0], value ? ` class="${value}"` : '')}>`;
    return value ? `<body class="${value}"${attrs}>` : tag;
  });
}

/** Write the nav, footer and chrome CSS into one page's markers. */
export function applyChrome(html, page, file) {
  let out = replaceRegion(html, NAV_START, NAV_END, renderNav(page), file);
  out = replaceRegion(out, FOOTER_START, FOOTER_END, renderFooter(), file);
  out = replaceRegion(out, CSS_START, CSS_END, chromeCss, file);
  return setBodyClass(out, 'has-subnav', Boolean(page.subnav));
}

function main() {
  const checkOnly = process.argv.includes('--check');
  const pages = listPages();
  const stale = [];

  for (const [file, page] of Object.entries(pages)) {
    const original = read(file);
    const html = applyChrome(original, page, file);
    if (html === original) continue;
    if (checkOnly) stale.push(file);
    else writeFileSync(join(ROOT, file), html);
  }

  if (checkOnly && stale.length) {
    console.error('Page chrome is out of sync in:\n' + stale.map((f) => `  ${f}`).join('\n'));
    console.error('\nRun `node tools/build-chrome.mjs` and commit the result.');
    process.exit(1);
  }
  console.log(
    checkOnly
      ? `Nav and footer in sync across ${Object.keys(pages).length} pages.`
      : `Nav and footer written to ${Object.keys(pages).length} pages.`,
  );
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
