#!/usr/bin/env node
/**
 * Renders the shared navigation into every page listed in partials/nav.config.json.
 *
 *   node tools/build-nav.mjs           write the nav into each page
 *   node tools/build-nav.mjs --check   fail (exit 1) if any page is out of sync
 *
 * Pages are the build output as well as the source of truth for everything else,
 * so the generated markup lives between markers and nothing outside them is touched
 * (apart from the `has-subnav` body class, which the sub-nav depends on).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(join(ROOT, p), 'utf8');

const HTML_START = '<!-- nav:start — generated by tools/build-nav.mjs from partials/, do not edit -->';
const HTML_END = '<!-- nav:end -->';
const CSS_START = '/* nav:start — generated by tools/build-nav.mjs from partials/nav.css, do not edit */';
const CSS_END = '/* nav:end */';

const config = JSON.parse(read('partials/nav.config.json'));
const navTemplate = stripComment(read('partials/nav.html'));
const subnavTemplate = stripComment(read('partials/subnav.html'));
const navCss = read('partials/nav.css').trimEnd();

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const fill = (tpl, vars) => tpl.replace(/\{\{(\w+)\}\}/g, (_, k) => (k in vars ? vars[k] : ''));
const indent = (lines, pad) => lines.map((l) => pad + l).join('\n');

/** Drop the leading explanatory comment from a partial — it is for editors, not output. */
function stripComment(tpl) {
  return tpl.replace(/^<!--[\s\S]*?-->\n/, '').trimEnd();
}

function renderNav(page) {
  const link = (l, cls) => `<a href="${esc(l.href)}" class="${cls}">${esc(l.label)}</a>`;
  const deskCls = 'text-sm text-slate-400 hover:text-white transition-colors';
  const mobCls = 'block text-sm text-slate-400 hover:text-white py-2';

  /** Emit a group heading whenever `group` changes, so products read as products. */
  const heading = (s, i, cls) =>
    s.group && s.group !== config.solutions[i - 1]?.group
      ? [`<p class="${cls} text-[11px] font-semibold uppercase tracking-wider text-slate-500">${esc(s.group)}</p>`]
      : [];

  const solutionsDesktop = config.solutions.map((s, i) => {
    const current = s.key === page.active;
    const wrap = current
      ? 'flex items-start gap-3 p-2.5 rounded-xl bg-white/[0.06] ring-1 ring-white/10 transition-colors'
      : 'flex items-start gap-3 p-2.5 rounded-xl hover:bg-white/5 transition-colors';
    return [
      ...heading(s, i, 'px-2.5 pt-2 pb-1'),
      `<a href="${esc(s.href)}" class="${wrap}"${current ? ' aria-current="page"' : ''}>`,
      `  <div class="w-8 h-8 rounded-lg flex items-center justify-center bg-${s.color}-500/10 border border-${s.color}-500/20 flex-shrink-0 mt-0.5">`,
      `    <i data-lucide="${esc(s.icon)}" class="w-4 h-4 text-${s.color}-400"></i>`,
      '  </div>',
      '  <div class="min-w-0">',
      `    <p class="text-sm font-semibold text-white">${esc(s.title)}</p>`,
      `    <p class="text-xs text-slate-400 truncate">${esc(s.subtitle)}</p>`,
      '  </div>',
      '</a>',
    ];
  });

  const solutionsMobile = config.solutions.map((s, i) => [
    ...heading(s, i, 'pt-2 pb-0.5'),
    `<a href="${esc(s.href)}" class="block py-1 text-sm text-slate-300 hover:text-white"${s.key === page.active ? ' aria-current="page"' : ''}>` +
      `<span class="font-medium text-white">${esc(s.title)}</span> ` +
      `<span class="text-xs text-slate-400">&middot; ${esc(s.subtitleShort)}</span></a>`,
  ]);

  return fill(navTemplate, {
    LINKS_BEFORE_DESKTOP: indent(config.linksBefore.map((l) => link(l, deskCls)), '      '),
    LINKS_AFTER_DESKTOP: indent(config.linksAfter.map((l) => link(l, deskCls)), '      '),
    LINKS_BEFORE_MOBILE: indent(config.linksBefore.map((l) => link(l, mobCls)), '        '),
    LINKS_AFTER_MOBILE: indent(config.linksAfter.map((l) => link(l, mobCls)), '        '),
    SOLUTIONS_DESKTOP: indent(solutionsDesktop.flat(), '            '),
    SOLUTIONS_MOBILE: indent(solutionsMobile.flat(), '            '),
    CTA_HREF: esc(config.cta.href),
    CTA_LABEL: esc(config.cta.label),
    SUBNAV: page.subnav ? renderSubnav(page.subnav) : '',
  });
}

function renderSubnav(sub) {
  const links = sub.links.map(
    (l) => `<a href="${esc(l.href)}" class="text-sm text-slate-400 hover:text-white transition-colors whitespace-nowrap">${esc(l.label)}</a>`,
  );
  return fill(subnavTemplate, {
    SUBNAV_HREF: esc(sub.href),
    SUBNAV_NAME: esc(sub.name),
    SUBNAV_LINKS: indent(links, '      '),
    SUBNAV_CTA_HREF: esc(sub.cta.href),
    SUBNAV_CTA_LABEL: esc(sub.cta.label),
  });
}

/** Replace the region between `start` and `end` markers. Throws if they are missing. */
function replaceRegion(html, start, end, body, file) {
  const a = html.indexOf(start);
  const b = html.indexOf(end, a);
  if (a === -1 || b === -1) {
    throw new Error(`${file}: missing ${start.slice(0, 14)}…${end} markers — add them around the nav block.`);
  }
  return html.slice(0, a) + start + '\n' + body + '\n' + html.slice(b);
}

function setBodyClass(html, cls, enabled) {
  return html.replace(/<body([^>]*)>/, (tag, attrs) => {
    const m = attrs.match(/\sclass="([^"]*)"/);
    const names = new Set(m ? m[1].split(/\s+/).filter(Boolean) : []);
    enabled ? names.add(cls) : names.delete(cls);
    const value = [...names].join(' ');
    if (m) return `<body${attrs.replace(m[0], value ? ` class="${value}"` : '')}>`;
    return value ? `<body class="${value}"${attrs}>` : tag;
  });
}

const checkOnly = process.argv.includes('--check');
const stale = [];

for (const [file, page] of Object.entries(config.pages)) {
  const original = read(file);
  let html = replaceRegion(original, HTML_START, HTML_END, renderNav(page), file);
  html = replaceRegion(html, CSS_START, CSS_END, navCss, file);
  html = setBodyClass(html, 'has-subnav', Boolean(page.subnav));

  if (html === original) continue;
  if (checkOnly) stale.push(file);
  else writeFileSync(join(ROOT, file), html);
}

if (checkOnly && stale.length) {
  console.error('Navigation is out of sync in:\n' + stale.map((f) => `  ${f}`).join('\n'));
  console.error('\nRun `node tools/build-nav.mjs` and commit the result.');
  process.exit(1);
}
console.log(
  checkOnly
    ? `Navigation in sync across ${Object.keys(config.pages).length} pages.`
    : `Navigation written to ${Object.keys(config.pages).length} pages.`,
);
